export const data = [
    {
        first: 'ejemploparaHacer un test [0, 0]',
        second: 'ejemploparaHacer un test [0, 1]',
        '3a': 'ejemploparaHacer un test [0, 2]',
        '4a': 'ejemploparaHacer un test [0, 3]',
        '5a': 'ejemploparaHacer un test [0, 4]',
        '6a': 'ejemploparaHacer un test [0, 5]',
        '7a': 'ejemploparaHacer un test [0, 6]',
        '8a': 'ejemploparaHacer un test [0, 7]',
        '9a': 'ejemploparaHacer un test [0, 8]',
    },
    {
        first: 'ejemploparaHacer un test [1, 0]',
        second: 'ejemploparaHacer un test [1, 1]',
        '3a': 'ejemploparaHacer un test [1, 2]',
        '4a': 'ejemploparaHacer un test [1, 3]',
        '5a': 'ejemploparaHacer un test [1, 4]',
        '6a': 'ejemploparaHacer un test [1, 5]',
        '7a': 'ejemploparaHacer un test [1, 6]',
        '8a': 'ejemploparaHacer un test [1, 7]',
        '9a': 'ejemploparaHacer un test [1, 8]',
    },
    {
        first: 'ejemploparaHacer un test [2, 0]',
        second: 'ejemploparaHacer un test [2, 1]',
        '3a': 'ejemploparaHacer un test [2, 2]',
        '4a': 'ejemploparaHacer un test [2, 3]',
        '5a': 'ejemploparaHacer un test [2, 4]',
        '6a': 'ejemploparaHacer un test [2, 5]',
        '7a': 'ejemploparaHacer un test [2, 6]',
        '8a': 'ejemploparaHacer un test [2, 7]',
        '9a': 'ejemploparaHacer un test [2, 8]',
    },
    {
        first: 'ejemploparaHacer un test [3, 0]',
        second: 'ejemploparaHacer un test [3, 1]',
        '3a': 'ejemploparaHacer un test [3, 2]',
        '4a': 'ejemploparaHacer un test [3, 3]',
        '5a': 'ejemploparaHacer un test [3, 4]',
        '6a': 'ejemploparaHacer un test [3, 5]',
        '7a': 'ejemploparaHacer un test [3, 6]',
        '8a': 'ejemploparaHacer un test [3, 7]',
        '9a': 'ejemploparaHacer un test [3, 8]',
    },
    {
        first: 'ejemploparaHacer un test [4, 0]',
        second: 'ejemploparaHacer un test [4, 1]',
        '3a': 'ejemploparaHacer un test [4, 2]',
        '4a': 'ejemploparaHacer un test [4, 3]',
        '5a': 'ejemploparaHacer un test [4, 4]',
        '6a': 'ejemploparaHacer un test [4, 5]',
        '7a': 'ejemploparaHacer un test [4, 6]',
        '8a': 'ejemploparaHacer un test [4, 7]',
        '9a': 'ejemploparaHacer un test [4, 8]',
    },
    {
        first: 'ejemploparaHacer un test [5, 0]',
        second: 'ejemploparaHacer un test [5, 1]',
        '3a': 'ejemploparaHacer un test [5, 2]',
        '4a': 'ejemploparaHacer un test [5, 3]',
        '5a': 'ejemploparaHacer un test [5, 4]',
        '6a': 'ejemploparaHacer un test [5, 5]',
        '7a': 'ejemploparaHacer un test [5, 6]',
        '8a': 'ejemploparaHacer un test [5, 7]',
        '9a': 'ejemploparaHacer un test [5, 8]',
    },
    {
        first: 'ejemploparaHacer un test [6, 0]',
        second: 'ejemploparaHacer un test [6, 1]',
        '3a': 'ejemploparaHacer un test [6, 2]',
        '4a': 'ejemploparaHacer un test [6, 3]',
        '5a': 'ejemploparaHacer un test [6, 4]',
        '6a': 'ejemploparaHacer un test [6, 5]',
        '7a': 'ejemploparaHacer un test [6, 6]',
        '8a': 'ejemploparaHacer un test [6, 7]',
        '9a': 'ejemploparaHacer un test [6, 8]',
    },
    {
        first: 'ejemploparaHacer un test [7, 0]',
        second: 'ejemploparaHacer un test [7, 1]',
        '3a': 'ejemploparaHacer un test [7, 2]',
        '4a': 'ejemploparaHacer un test [7, 3]',
        '5a': 'ejemploparaHacer un test [7, 4]',
        '6a': 'ejemploparaHacer un test [7, 5]',
        '7a': 'ejemploparaHacer un test [7, 6]',
        '8a': 'ejemploparaHacer un test [7, 7]',
        '9a': 'ejemploparaHacer un test [7, 8]',
    },
    {
        first: 'ejemploparaHacer un test [8, 0]',
        second: 'ejemploparaHacer un test [8, 1]',
        '3a': 'ejemploparaHacer un test [8, 2]',
        '4a': 'ejemploparaHacer un test [8, 3]',
        '5a': 'ejemploparaHacer un test [8, 4]',
        '6a': 'ejemploparaHacer un test [8, 5]',
        '7a': 'ejemploparaHacer un test [8, 6]',
        '8a': 'ejemploparaHacer un test [8, 7]',
        '9a': 'ejemploparaHacer un test [8, 8]',
    },
    {
        first: 'ejemploparaHacer un test [9, 0]',
        second: 'ejemploparaHacer un test [9, 1]',
        '3a': 'ejemploparaHacer un test [9, 2]',
        '4a': 'ejemploparaHacer un test [9, 3]',
        '5a': 'ejemploparaHacer un test [9, 4]',
        '6a': 'ejemploparaHacer un test [9, 5]',
        '7a': 'ejemploparaHacer un test [9, 6]',
        '8a': 'ejemploparaHacer un test [9, 7]',
        '9a': 'ejemploparaHacer un test [9, 8]',
    },
    {
        first: 'ejemploparaHacer un test [10, 0]',
        second: 'ejemploparaHacer un test [10, 1]',
        '3a': 'ejemploparaHacer un test [10, 2]',
        '4a': 'ejemploparaHacer un test [10, 3]',
        '5a': 'ejemploparaHacer un test [10, 4]',
        '6a': 'ejemploparaHacer un test [10, 5]',
        '7a': 'ejemploparaHacer un test [10, 6]',
        '8a': 'ejemploparaHacer un test [10, 7]',
        '9a': 'ejemploparaHacer un test [10, 8]',
    },
    {
        first: 'ejemploparaHacer un test [11, 0]',
        second: 'ejemploparaHacer un test [11, 1]',
        '3a': 'ejemploparaHacer un test [11, 2]',
        '4a': 'ejemploparaHacer un test [11, 3]',
        '5a': 'ejemploparaHacer un test [11, 4]',
        '6a': 'ejemploparaHacer un test [11, 5]',
        '7a': 'ejemploparaHacer un test [11, 6]',
        '8a': 'ejemploparaHacer un test [11, 7]',
        '9a': 'ejemploparaHacer un test [11, 8]',
    },
    {
        first: 'ejemploparaHacer un test [12, 0]',
        second: 'ejemploparaHacer un test [12, 1]',
        '3a': 'ejemploparaHacer un test [12, 2]',
        '4a': 'ejemploparaHacer un test [12, 3]',
        '5a': 'ejemploparaHacer un test [12, 4]',
        '6a': 'ejemploparaHacer un test [12, 5]',
        '7a': 'ejemploparaHacer un test [12, 6]',
        '8a': 'ejemploparaHacer un test [12, 7]',
        '9a': 'ejemploparaHacer un test [12, 8]',
    },
    {
        first: 'ejemploparaHacer un test [13, 0]',
        second: 'ejemploparaHacer un test [13, 1]',
        '3a': 'ejemploparaHacer un test [13, 2]',
        '4a': 'ejemploparaHacer un test [13, 3]',
        '5a': 'ejemploparaHacer un test [13, 4]',
        '6a': 'ejemploparaHacer un test [13, 5]',
        '7a': 'ejemploparaHacer un test [13, 6]',
        '8a': 'ejemploparaHacer un test [13, 7]',
        '9a': 'ejemploparaHacer un test [13, 8]',
    },
    {
        first: 'ejemploparaHacer un test [14, 0]',
        second: 'ejemploparaHacer un test [14, 1]',
        '3a': 'ejemploparaHacer un test [14, 2]',
        '4a': 'ejemploparaHacer un test [14, 3]',
        '5a': 'ejemploparaHacer un test [14, 4]',
        '6a': 'ejemploparaHacer un test [14, 5]',
        '7a': 'ejemploparaHacer un test [14, 6]',
        '8a': 'ejemploparaHacer un test [14, 7]',
        '9a': 'ejemploparaHacer un test [14, 8]',
    },
    {
        first: 'ejemploparaHacer un test [15, 0]',
        second: 'ejemploparaHacer un test [15, 1]',
        '3a': 'ejemploparaHacer un test [15, 2]',
        '4a': 'ejemploparaHacer un test [15, 3]',
        '5a': 'ejemploparaHacer un test [15, 4]',
        '6a': 'ejemploparaHacer un test [15, 5]',
        '7a': 'ejemploparaHacer un test [15, 6]',
        '8a': 'ejemploparaHacer un test [15, 7]',
        '9a': 'ejemploparaHacer un test [15, 8]',
    },
    {
        first: 'ejemploparaHacer un test [16, 0]',
        second: 'ejemploparaHacer un test [16, 1]',
        '3a': 'ejemploparaHacer un test [16, 2]',
        '4a': 'ejemploparaHacer un test [16, 3]',
        '5a': 'ejemploparaHacer un test [16, 4]',
        '6a': 'ejemploparaHacer un test [16, 5]',
        '7a': 'ejemploparaHacer un test [16, 6]',
        '8a': 'ejemploparaHacer un test [16, 7]',
        '9a': 'ejemploparaHacer un test [16, 8]',
    },
    {
        first: 'ejemploparaHacer un test [17, 0]',
        second: 'ejemploparaHacer un test [17, 1]',
        '3a': 'ejemploparaHacer un test [17, 2]',
        '4a': 'ejemploparaHacer un test [17, 3]',
        '5a': 'ejemploparaHacer un test [17, 4]',
        '6a': 'ejemploparaHacer un test [17, 5]',
        '7a': 'ejemploparaHacer un test [17, 6]',
        '8a': 'ejemploparaHacer un test [17, 7]',
        '9a': 'ejemploparaHacer un test [17, 8]',
    },
    {
        first: 'ejemploparaHacer un test [18, 0]',
        second: 'ejemploparaHacer un test [18, 1]',
        '3a': 'ejemploparaHacer un test [18, 2]',
        '4a': 'ejemploparaHacer un test [18, 3]',
        '5a': 'ejemploparaHacer un test [18, 4]',
        '6a': 'ejemploparaHacer un test [18, 5]',
        '7a': 'ejemploparaHacer un test [18, 6]',
        '8a': 'ejemploparaHacer un test [18, 7]',
        '9a': 'ejemploparaHacer un test [18, 8]',
    },
    {
        first: 'ejemploparaHacer un test [19, 0]',
        second: 'ejemploparaHacer un test [19, 1]',
        '3a': 'ejemploparaHacer un test [19, 2]',
        '4a': 'ejemploparaHacer un test [19, 3]',
        '5a': 'ejemploparaHacer un test [19, 4]',
        '6a': 'ejemploparaHacer un test [19, 5]',
        '7a': 'ejemploparaHacer un test [19, 6]',
        '8a': 'ejemploparaHacer un test [19, 7]',
        '9a': 'ejemploparaHacer un test [19, 8]',
    },
];


